### ISSUE TITLE
param_group is wrong set?

### ISSUE THREAD

**Issue by Johnson-yue** [zer0int/CLIP-fine-tune#13]
https://github.com/zer0int/CLIP-fine-tune/blob/c92f265d0d3d7abd6d6591657375aabc10eeb112/ft-B-train-OpenAI-CLIP-ViT-L-14.py#L255-L260

why visual_parameter using transform_parameter compute length, and then transformer_parameter using visual_parameter compute length ?

**Comment by zer0int** [comment]
Fortunately, that wasn't in use, but just an example - however, a terrible example indeed. I should just make a habit of giving all code to AI for review, haha. Thank you for pointing it out!
