### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by T8mars** [zer0int/CLIP-fine-tune#2]
File "D:\ComfyUI-aki\ComfyUI-aki-v1.2_T8\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ComfyUI-aki\\ComfyUI-aki-v1.2_T8\\custom_nodes\\CLIP-fine-tune\\__init__.py'

Cannot import D:\ComfyUI-aki\ComfyUI-aki-v1.2_T8\custom_nodes\CLIP-fine-tune module for custom nodes: [Errno 2] No such file or directory: 'D:\\ComfyUI-aki\\ComfyUI-aki-v1.2_T8\\custom_nodes\\CLIP-fine-tune\\__init__.py'
[94m[Allor][0m: No new updates.
[92m[Allor][0m: 0 nodes were overridden.
[92m[Allor][0m: 12 modules were enabled.
[92m[Allor][0m: 98 nodes were loaded.
[AnimateDiff] - [0;33mWARNING[0m - xformers is enabled but it has a bug that can cause issue while using with AnimateDiff.
[36;20m[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\ComfyUI-aki\ComfyUI-aki-v1.2_T8\custom_nodes\comfyui_controlnet_aux\ckpts[0m
[36;20m[custom_nodes.comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
[36;20m[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
DWPose: Onnxruntime with acceleration providers detected
Adding 
D:\ComfyUI-aki\ComfyUI-aki-v1.2_T8\custom_nodes to sys.path

**Comment by zer0int** [comment]
Sorry, this repo does not have any custom nodes for ComfyUI; it's for fine-tuning CLIP (via the command line, independent of ComfyUI)! To use your fine-tune with ComfyUI:

If you fine-tuned a GmP-CLIP via the "exp-ft*" scripts, first use this:
exp-ft-C-convert-GmP-back-to-weight.py
And then:
ft-C-convert-for-SDXL-comfyUI-OpenAI-CLIP.py

Likewise, if you have a "normal" (no GmP) fine-tune, simply use this:
ft-C-convert-for-SDXL-comfyUI-OpenAI-CLIP.py

This will give you a "state_dict" file you can then plug into SDXL etc. via ComfUI (without the need for adding any custom nodes etc.):

![dualclip](https://github.com/zer0int/CLIP-fine-tune/assets/132047210/11da84af-fd61-4f95-8bd3-832dacf8b1c4)

Please scroll all the way down in the readme on my repo; I outlined the full steps to "plug your fine-tune into ComfyUI" there.
